# Generated by Django 4.2 on 2023-04-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_tee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_played", models.DateTimeField()),
                (
                    "holes_played",
                    models.CharField(
                        choices=[("9", "9 Holes"), ("18", "18 Holes")],
                        default="9",
                        max_length=64,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.golfcourse",
                    ),
                ),
            ],
        ),
    ]
