# Generated by Django 4.2 on 2023-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="hole",
            name="par",
            field=models.IntegerField(default=3),
        ),
    ]
