# Generated by Django 4.2 on 2023-04-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
        migrations.RemoveField(
            model_name="holescore",
            name="game",
        ),
        migrations.DeleteModel(
            name="UserGameLink",
        ),
    ]
