# Generated by Django 4.2 on 2023-04-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_player_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup", "Setup"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="setup",
                max_length=64,
            ),
        ),
    ]
