# Generated by Django 4.2 on 2023-05-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_hole_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeeTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tee_time", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.golfcourse",
                    ),
                ),
                ("players", models.ManyToManyField(to="home.player")),
            ],
        ),
    ]
