# Generated by Django 4.2 on 2023-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_teetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="teetime",
            name="holes_to_play",
            field=models.CharField(
                choices=[("9", "9 Holes"), ("18", "18 Holes")],
                default="9",
                max_length=64,
            ),
        ),
    ]
