# Generated by Django 4.2 on 2023-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_game_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="league_game",
            field=models.BooleanField(default=False),
        ),
    ]
