# Generated by Django 4.2 on 2023-05-30 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0019_alter_game_date_played"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
