# Generated by Django 4.2 on 2023-06-03 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0020_player_added_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "user_account")},
        ),
    ]
