# Generated by Django 4.2 on 2023-07-11 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0022_alter_player_unique_together_alter_player_added_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("name", "added_by")},
        ),
    ]
